// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsLMbA7DRZKnIFDRHvWoWy2ny1IuXefEw',
    appId: '1:223305086511:web:6056996c84c424d86cb8da',
    messagingSenderId: '223305086511',
    projectId: 'flutter-pradeep-f14c6',
    authDomain: 'flutter-pradeep-f14c6.firebaseapp.com',
    storageBucket: 'flutter-pradeep-f14c6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7iCCvHuZghRQeThZzFPBf9OwX9n1D0Q4',
    appId: '1:223305086511:android:83ea8fbdb15ac8396cb8da',
    messagingSenderId: '223305086511',
    projectId: 'flutter-pradeep-f14c6',
    storageBucket: 'flutter-pradeep-f14c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWt_IwdOxbv-caYnDNZgFYKG-7p1r-dxc',
    appId: '1:223305086511:ios:33d52ce5d0c8588d6cb8da',
    messagingSenderId: '223305086511',
    projectId: 'flutter-pradeep-f14c6',
    storageBucket: 'flutter-pradeep-f14c6.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWt_IwdOxbv-caYnDNZgFYKG-7p1r-dxc',
    appId: '1:223305086511:ios:428376efb353b5a36cb8da',
    messagingSenderId: '223305086511',
    projectId: 'flutter-pradeep-f14c6',
    storageBucket: 'flutter-pradeep-f14c6.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
